# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_n_kh <- function(X, Z, H, K) {
    .Call(`_TopSpace_calculate_n_kh`, X, Z, H, K)
}

calculate_m_ik <- function(Z, K) {
    .Call(`_TopSpace_calculate_m_ik`, Z, K)
}

update_Z <- function(Z, X, theta, n_kh, m_ik, gamma) {
    .Call(`_TopSpace_update_Z`, Z, X, theta, n_kh, m_ik, gamma)
}

update_beta <- function(n_kh, gamma) {
    .Call(`_TopSpace_update_beta`, n_kh, gamma)
}

update_alpha <- function(m_ik, theta) {
    .Call(`_TopSpace_update_alpha`, m_ik, theta)
}

dU_tilde <- function(B, alpha, theta, Bases, lambda, n_subsample) {
    .Call(`_TopSpace_dU_tilde`, B, alpha, theta, Bases, lambda, n_subsample)
}

update_B <- function(B, nu, alpha, Bases, lambda, n_leapfrog, n_subsample, rho, eta) {
    .Call(`_TopSpace_update_B`, B, nu, alpha, Bases, lambda, n_leapfrog, n_subsample, rho, eta)
}

calculate_deviance <- function(X, beta, alpha) {
    .Call(`_TopSpace_calculate_deviance`, X, beta, alpha)
}

